### ISSUE TITLE
Nord (NordVPN) domains

### ISSUE THREAD

**Issue by felipecrs** [apple/password-manager-resources#342] opened 2020-09-09 04:01 UTC
nordaccount.com
nordvpn.com
nordpass.com

**Comment by xXEmMuonLaiChiXx** [comment] 2020-09-10 05:16
[]()]()

**Comment by ChrisMarstaller** [comment] 2021-03-22 20:54
Duplicate of #401

**Comment by aabosh** [comment] 2022-05-03 13:57
This has been addressed, so I'm closing the issue. If I missed something, please feel free to create a new issue!

**Closed by aabosh** 2022-05-03 13:57 UTC
